config/routes.rb
Rails.application.routes.draw do

	devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users
  
  root to: 'home#index'
  ActiveAdmin.routes(self)

end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  validates_presence_of :email
  # mount_uploader :image, ImageUploader
  has_many :authorizations

  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
    if authorization.user.blank?
      user = current_user || User.where('email = ?', auth["info"]["email"]).first
      if user.blank?
       user = User.new
       user.password = Devise.friendly_token[0,10]
       user.name = auth.info.name
       user.email = auth.info.email
       if auth.provider == "twitter" 
         user.save(:validate => false) 
       else
         user.save
       end
     end
     authorization.username = auth.info.nickname
     authorization.user_id = user.id
     authorization.save
   end
   authorization.user
 end
 
end

app/models/users.rb
class Users < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# from the devise social-login-in-rails
	before_action :set_user
	before_action :validate_authorization_for_user, only: [:edit, :update]

  def show
  end

  def edit
  end

  def index
  	@users = User.all
  end

  def update
  	if @user.update_attributes(user_params)
  		redirect_to @user, notice: "User has been successfully updated."
  	else
  		render action: 'edit'
  	end
  end

  # def create
  #   @user = User.new(user_params)
  #   @user = current_user
  #   if @user.save
  #     log_in @user
  #     flash[:success] = 'Welcome to Coder Closet -- where the important programmers throw their threads.'
  #     redirect_to @user
  #   else
  #     render 'new'
  #   end
  # end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def validate_authorization_for_user
  	redirect_to root_path unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:name, :user, :about)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :required => true, :autofocus => true %>
    <%= f.input :about, :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<div>
Connect Account



<% ['facebook', 'twitter', 'github', 'linkedin', 'google_oauth2'].each do |provider| %>

  <% if current_user.authorizations.pluck(:provider).include?(provider.to_s) %>
    <%= provider.to_s.titleize %> Connected
  <% else %>
      <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path('user', provider) %>
  <% end %>
<br/>
<% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
	  <%= (image_tag @user.image_url(:thumb).to_s) %>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>